# .github/ISSUE_TEMPLATE/config.yml

# Whether or not to allow the creation of a completely blank issue
blank_issues_enabled: false

# An external link that appears when a user clicks on "New issue".
contact_links:
  - name: Documentation
    url: https://doc.empasy.com
    about: Please consult the documentation first, your question may already have an answer.
  - name: 🤔 Questions & Discussions
    url: https://github.com/orgs/DramaticCollaboration/
    about: If you have a question or idea to discuss, please create a new issue.
