name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

# Set permissions for GITHUB_TOKEN to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, cancel running workflows/jobs (if new push happens)
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # Ensure consistency with CI steps

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Ensure consistency with CI steps
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm docs:build
        # If your build output directory is not docs/.vuepress/dist
        # Please modify the path in the actions/upload-pages-artifact step below

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Specify the build output directory
          path: 'docs/.vuepress/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
